name: Tap install

on:
  push:
    branches:
      - master

jobs:
  install_from_tap:
    runs-on: macos-latest
    steps:
    - name: Add Mysh tap
      run: brew tap mishamyrt/mysh
    - name: Install Mysh
      run: brew install mysh
